package com.melvic.lohika.parsers

object Lexemes:
  val Iff = "<->"
  val Imply = "->"
  val Or = "|"
  val And = "&"
  val Not = "!"
  val True = "true"
  val False = "false"
  val Forall = "A:"
  val ThereExists = "E:"
  val LeftParen = "("
  val RightParen = ")"
  val Entailment = "|="
  val Const = "'"
  val LeftBracket = "["
  val RightBracket = "]"
  val DefinedAs = ":="
  val StmtDelimiter = ";"
  val PremisesDelimiter = ","
  val Comment = "#"
